spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sannareddy/configserver
          username: thevamsi@live.com
          password: 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
          clone-on-start: true
          default-label: main
  application:
    name: configserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8012
management:
  endpoints:
    web:
      exposure:
        include:
        - busrefresh
        - busenv