server:
  port: 0
spring:
  application:
    name: userservice
  jpa:
    hibernate:
      ddl-auto: update  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      
  datasource:
#    url: jdbc:h2:mem:testdb
     url: jdbc:mysql://localhost:3306/microservices
     username: root
     password: admin    
  config:
    import:
    - optional:configserver:http://localhost:8012
  cloud:
    config:
      name: configserver
#  zipkin:
#    base-url: http://localhost:9411    
eureka:
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true
logging:
  file:    
    name: userservice.log
login:
  url: /users/login       
management:
  endpoints:
    web:
      exposure:
        include:
        - mappings  